language: go
go_import_path: github.com/operator-framework/helm-app-operator-kit
sudo: required

services:
  - docker

jobs:
  include:
    - before_script: helm-app-operator/hack/ci/setup-openshift.sh
      env: CLUSTER=openshift
      script: make -C helm-app-operator test/e2e
      name: Helm on OpenShift

install:
- curl -Lo dep https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 && chmod +x dep && sudo mv dep /usr/local/bin/
- make -C helm-app-operator dep test/sanity test/unit build


after_success:
- echo "Build succeeded, operator was generated, memcached operator is running on $CLUSTER, and unit/integration tests passed"

after_failure:
- echo "Build failed, operator failed to generate, memcached operator is not running on $CLUSTER, and unit/integration tests failed"
