kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-account-helm-app-operator
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: helm-app-operator
  apiGroup: rbac.authorization.k8s.io
